### ISSUE TITLE
Composed directives must be consistently named across subgraph implementations and not use `@federation__` prefix

### ISSUE THREAD

**Issue by prasek** [apollographql/apollo-federation-subgraph-compatibility#125]
Composed directives like @inaccessible and @tag must not use `@federation__` prefix and be consistently named across subgraph implementations.

See comments in:
- https://github.com/apollographql/federation/issues/1976

We should update the compatibility tests to ensure this.

**Comment by hwillson** [comment]
Related:

- https://github.com/apollographql/federation/issues/1971
- https://github.com/apollographql/federation/issues/1972

**Comment by hwillson** [comment]
Summarizing the plan here:
- We're asking people to implement `@inaccessible` and `@tag` in the products schema so they wouldn't be adding `@federation__` directives directly, BUT Federation 2 doesn't currently support mixing the 2 different formats (for now - will fail at composition)
- We'll validate that the non-`@federation__` versions are used by subgraph libraries by checking to make sure they aren't included in the exposed (queries) SDL
