### ISSUE TITLE
Update @requires test to actually verify the functionality

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-federation-subgraph-compatibility#128]
README mentions the `@requires` test but currently `product` subgraph **DOES NOT** contains the directive. Currently `@requires` directive is specified in the `inventory` subgraph only which means that we are actually not testing the functionality against implementing libraries.

Proposed changes:
* update `Users` subgraph
```graphql
type User @key(fields:"email") {
  email:ID!
  name: String
  totalProductsCreated: Int
  yearsOfEmployment: Int! # <-- new field
}
```
* update `Products` subgraph to test `@requires` functionality
```graphql
extend type User @key(fields: "email") {
  averageProductsCreatedPerYear: Int @requires(fields: "yearsOfEmployment") # <-- test `@requires` functionality
  email: ID! @external
  name: String @override(from: "users")
  totalProductsCreated: Int @external
  yearsOfEmployment: Int! @external # <-- field from the users subgraph used by @requires
}
```

Updated implementations:

- [ ] absinthe-federation (Elixir)
- [x] apollo-server (JavaScript / TypeScript)
- [ ] appsync (AWS Hosted)
- [ ] ariadne (Python)
- [ ] async-graphql (Rust)
- [ ] caliban (Scala)
- [x] dgs (Java / Kotlin)
- [ ] express-graphql (JavaScript / TypeScript)
- [x] federation-jvm (Java / Kotlin)
- [ ] gqlgen (Go)
- [ ] graphene (Python)
- [ ] graphql-dotnet (C# / .NET)
- [x] graphql-java-kickstart (Java / Kotlin)
- [x] graphql-kotlin (Java / Kotlin)
- [ ] graphql-yoga (JavaScript / TypeScript)
- [ ] hotchocolate (C# / .NET)
- [ ] lighthouse (PHP)
- [ ] mercurius (JavaScript / TypeScript)
- [ ] nestjs (JavaScript / TypeScript)
- [ ] php (PHP)
- [ ] pothos (JavaScript / TypeScript)
- [ ] ruby (Ruby)
- [ ] stepzen (StepZen Hosted)
- [x] strawberry-graphql (Python)

**Comment by kdawgwilk** [comment]
I just realized while working on implementing this in `absinthe_federation` that because `averageProductsCreatedPerYear` needs data from `totalProductsCreated` and `yearsOfEmployment` and both of those fields are `@external` don't both of those fields need to be marked as required? e.g. `averageProductsCreatedPerYear: Int @requires(fields: "yearsOfEmployment totalProductsCreated")` because otherwise the gateway won't ever send the `totalProductsCreated` field to the products subgraph when resolving the `averageProductsCreatedPerYear` field?

**Comment by dariuszkuc** [comment]
Great question! In general yes, if we have a field that is calculated based on values of some other `external` fields then all those fields should be specified in `@requires` field set.

That being said, in our specific use case, `totalProductsCreated` field is a local field. `User` object is currently only accessible through `Product.createdBy` field that has `@provides(fields: "totalProductsCreated")` directive applied.

```graphql
type Product @key(fields: "id") {
  ... # fields omitted for clarity
  createdBy: User @provides(fields: "totalProductsCreated") # `totalProductsCreated` is a local field
}

extend type User @key(fields: "email") {
  averageProductsCreatedPerYear: Int @requires(fields: "yearsOfEmployment")
  email: ID! @external
  name: String @override(from: "users")
  # technically, this field does not have to be marked as external in fed 2 as it is only accessible through `@provides` path
  # if field was accessible through other non-provided paths then yes it should be marked as external and required
  # fed 1 does require the field to be marked as external
  totalProductsCreated: Int @external
  yearsOfEmployment: Int! @external
}
```

I'll update the docs to explicitly specify `@requires(fields: "totalProductsCreated yearsOfEmployment")` to avoid the confusion (and also ensure it all works in non `@provides` paths.... if we ever add them).

**Comment by dariuszkuc** [comment]
Created https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/160

**Comment by kdawgwilk** [comment]
Ah I didn't catch the `@provides` that makes sense 👍 I do like making that a bit more explicit though 🙏

**Comment by dariuszkuc** [comment]
Superseded by https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/166 that tracks both `@requires` and `@key` schema changes.
