### ISSUE TITLE
`@inaccessible` test is inconsistent with specification.

### ISSUE THREAD

**Issue by ddebrunner** [apollographql/apollo-federation-subgraph-compatibility#135]
The test for `@inaccessible` tests that the field `unit` marked with `@inaccessible` can be returned directly from products.
[@inaccessible](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/src/tests/inaccessible.test.ts#L17)

However the spec for `@inaccessible` says:
_The processor implementing [@inaccessible](https://specs.apollo.dev/inaccessible/v0.2/#@inaccessible) [must](https://tools.ietf.org/html/rfc2119#section-1) ensure that it returns a public‐facing API with all [@inaccessible](https://specs.apollo.dev/inaccessible/v0.2/#@inaccessible) items removed:_

I read that as `unit` must be removed from the public api and so should not be able to be selected.

https://specs.apollo.dev/inaccessible/v0.2/

Maybe it's because `@inaccessible` has a different definition here:
https://www.apollographql.com/docs/federation/federated-types/federated-directives#inaccessible

but it's unclear, since the actual [federation spec]( https://www.apollographql.com/docs/federation/federation-spec) does not list `@inaccessible` so I assume it's defined from https://specs.apollo.dev/inaccessible/v0.2/

**Comment by prasek** [comment]
@ddebrunner the spec you're looking at is for supergraph usage & is enforced at runtime in the supergraph Gateway/Router. 

Usage of `@inaccessible` in subgraphs hasn't been added to the subgraph spec yet, but that is being added and we'll make this supergraph vs. subgraph distinction more clear in the specs and appreciate you calling this out. 🙏 

from the https://github.com/apollographql/apollo-federation-subgraph-compatibility#testing-spec-compliance

## @inaccessible (in subgraphs)
Must be seen as a valid schema directive in the subgraph library service sdl. Is verified by checking for its inclusion in the query { _service { sdl } } result. Must also be able to query inaccessible fields from the Products schema.

**Comment by ddebrunner** [comment]
Thanks, that clears it up!
