### ISSUE TITLE
GO Federation Compatibility Testing Support - gqlgen

### ISSUE THREAD

**Issue by michael-watson** [apollographql/apollo-federation-subgraph-compatibility#17]

**Comment by ahmed-adly-khalil** [comment]
Hello, I wonder if there is an update on this? any luck with testing gqlgen for subgraph support?

**Comment by ahmed-adly-khalil** [comment]
@kdawgwilk Yeah i got it working as well, the only drawback i saw that there is no golang based gateway from the same team at 99designs, all examples are using apollo node gateway. There are some options in github but haven't tried it yet.

**Comment by ahmed-adly-khalil** [comment]
@ekhabarov might be able to help
