### ISSUE TITLE
Federation 2 support for async-graphql

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-federation-subgraph-compatibility#171]
It would be really great to help get Fed 2 support in place for `async-graphql`.

https://github.com/async-graphql/async-graphql/issues/982

**Comment by dgrijalva** [comment]
Reference:
https://www.apollographql.com/docs/federation/federation-2/new-in-federation-2

(Copied here for convenience from #922)

**Comment by damienpontifex** [comment]
Merged #199 which now has the updated schema tests for fed2. First step to being able to validate at least.

**Comment by dariuszkuc** [comment]
Resolved in https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/238
