### ISSUE TITLE
Add a test for @composeDirective

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-federation-subgraph-compatibility#175]
Spec details in https://github.com/apollographql/federation/pull/2065.

**Comment by hwillson** [comment]
Worth noting that we're no longer forcing custom directives to be defined within a core feature (`@link`) to use `@composeDirective`: https://github.com/apollographql/federation/pull/2234

This will change our tests (which we haven't started, so great timing 😅).

**Comment by dariuszkuc** [comment]
Resolved in #353
