### ISSUE TITLE
update AppSync example integration with the latest schema changes

### ISSUE THREAD

**Issue by dariuszkuc** [apollographql/apollo-federation-subgraph-compatibility#179]
See https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/166 for details.

**Comment by dariuszkuc** [comment]
@flochaz could you help us out with updating `AppSync` test integration with the latest schema changes?

**Comment by flochaz** [comment]
I can't make `@requires`  to work and looks like it's the same for a many other implementation: The first reason seems to be that the docker hub image used in docker-compose for users service (`apollo-federation-implementations/users`) does not implement new schema (especially `yearsOfEmployment`). But even using local implementation (https://github.com/apollographql/apollo-federation-subgraph-compatibility/tree/main/subgraphs/users) I end up with the following error, any suggestion ? 

```
{
  "data": {
    "product": {
      "createdBy": {
        "averageProductsCreatedPerYear": null
      }
    }
  },
  "errors": [
    {
      "message": "invalid content: Missing key `_entities`!",
      "locations": [],
      "path": [
        "product",
        "createdBy"
      ],
      "extensions": {
        "type": "ExecutionInvalidContent",
        "reason": "Missing key `_entities`!"
      }
    }
  ]
}
```

**Comment by dariuszkuc** [comment]
👋 Make sure to pull in the latest `main` and rebuild it locally using `npm run setup` - `apollo-federation-implementations/users` does [implement the latest schema](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/subgraphs/users/users.graphql). 

In order to test `averageProductsCreatedPerYear` make sure to run your queries through the router, since it `@requires(fields: "totalProductsCreated yearsOfEmployment")` those fields will only be populated if request flows through the router.

**Comment by flochaz** [comment]
will do this week
