### ISSUE TITLE
update pothos example integration with the latest schema changes

### ISSUE THREAD

**Issue by dariuszkuc** [apollographql/apollo-federation-subgraph-compatibility#194]
See #166 for details.

**Comment by dariuszkuc** [comment]
@hayes could you help us out with updating `pothos` test integration with the latest schema changes?

**Comment by hayes** [comment]
@dariuszkuc opened a PR, let me know if that works.  Didn't update the main readme, but tests seem to pass

**Comment by dariuszkuc** [comment]
Awesome! Thanks!
