### ISSUE TITLE
For Maintainers, have a way where in their repo CI to test against the spec

### ISSUE THREAD

**Issue by michael-watson** [apollographql/apollo-federation-subgraph-compatibility#22]
It would be nice to have a CLI-like tool to invoke this test from CI.

- Complete abstracting test framework

This would help individual libraries prevent releasing something that breaks the spec vs catching the break after the release

**Comment by myronmarston** [comment]
👋  We'd also like this.  I chatted with @lennyburdette a bit about this and he mentioned the possibility of providing something like:

```
$ npx validate-subgraph --url http://localhost:4001
```

So consider this adding my vote for this :).

**Comment by kdawgwilk** [comment]
Also, quite a few of these libraries use GitHub actions so an action plugin to make that setup easy might also be useful

**Comment by dariuszkuc** [comment]
Hello 👋 
Compatibility test scripts are now externalized and available through an executable NPM script (https://www.npmjs.com/package/@apollo/federation-subgraph-compatibility) and Github Action (https://github.com/marketplace/actions/apollo-federation-subgraph-compatibility).
