### ISSUE TITLE
100% Fed 2 compliance for all tested subgraphs

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-federation-subgraph-compatibility#225]
We need to update the following projects in the subgraph testing repo to fully support Federation 2:

- [ ] Graphene
- [ ] GraphQL .Net
- [ ] Hot Chocolate 
- [ ] Lighthouse
- [x] Mercurius
- [ ] apollo-federation-php
- [ ] gqlgen
- [ ] graphql-ruby
- [x] async-graphql
- [ ] GraphQL java kickstart

Note that there is some overlap here with https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/166.

**Comment by rvanlaak** [comment]
@dariuszkuc agreed, I've added https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/442
