### ISSUE TITLE
Add Dgraph to the testing repo

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-federation-subgraph-compatibility#230]
Dgraph supports Federation (https://dgraph.io/docs/graphql/federation/). Let's add them in. They likely won't meet full Federation 2 requirements, but we can look into helping with that after the initial test are in place.

**Comment by dariuszkuc** [comment]
We should be able to add the support but I think it would require starting up multiple docker containers.

- Dgraph base image (empty schema)
- script to initialize Dgraph with schema and populates it with data
- Dgraph lambda for custom resolvers (e.g. to support `@requires`)
- most likely will also need a proxy to remap `/graphl` endpoint to just `/` (based on their docs this endpoint does not appear to be configurable)

**Comment by dariuszkuc** [comment]
PR: https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/253

**Comment by dariuszkuc** [comment]
PR merged
