### ISSUE TITLE
Java Federation Compatibility Testing Support - graphql-java-tools

### ISSUE THREAD

**Issue by setchy** [apollographql/apollo-federation-subgraph-compatibility#24]
- Support for [graphql-java-tools](https://github.com/graphql-java-kickstart/graphql-java-tools) / [graphql-spring-boot](https://github.com/graphql-java-kickstart/graphql-spring-boot)
- [apollographql/federation-jvm graphql-java-tools sample ](https://github.com/apollographql/federation-jvm/tree/master/spring-example/src/main/java/com/apollographql/federation/springexample/graphqljavatools)

**Comment by michael-watson** [comment]
Good callout @setchy, for the initial release I stripped it down to 1 sample but I'm sure we can get this added in quickly

**Comment by setchy** [comment]
Redundant now that `federation-jvm` compatibility tests are incorporated
