### ISSUE TITLE
Spec and a compatibility repo for supergraphs

### ISSUE THREAD

**Issue by enisdenjo** [apollographql/apollo-federation-subgraph-compatibility#251]
It would be great if a repo like this one would exist for checking the compatibility of supergraphs as well.

Additionally, a spec of features that such a service has to implement would be great too (maybe there's already one?).

**Comment by hwillson** [comment]
👋 @enisdenjo - thanks for the suggestion! This isn't something we're considering at this time unfortunately. We're staying focused on testing subgraphs for now, including looking into ways to make subgraph testing easier for library authors (like giving people a way to run the Federation test suites from this repo in their own CI/CD). We'll definitely keep you posted if this changes - thanks!
