### ISSUE TITLE
Provide a way for subgraph authors to run Federation tests in their repos

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-federation-subgraph-compatibility#252]
It would be awesome if we can provide a way for subgraph library authors to include the Federation tests from this repo in their own projects / repos, so they can be included as part of their own CI/CD.

**Comment by dariuszkuc** [comment]
Tests can now be run through [NPM script](https://www.npmjs.com/package/@apollo/federation-subgraph-compatibility) and [Github Action](https://github.com/marketplace/actions/apollo-federation-subgraph-compatibility).

Blog post -> https://www.apollographql.com/blog/backend/testing/new-apollo-federation-spec-compliance-tools-for-graphql-server-maintainers/
