### ISSUE TITLE
False negatives on `requires`, `shareable` and `override` tests

### ISSUE THREAD

**Issue by enisdenjo** [apollographql/apollo-federation-subgraph-compatibility#336]
The following tests yield a false negative when testing using the `@apollo/federation-subgraph-compatibility` CLI ([see the GitHub Action job](https://github.com/dotansimha/graphql-yoga/actions/runs/4045217954/jobs/6956400493)):

1. [requires.test](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/packages/compatibility/src/tests/requires.test.ts)
1. [shareable.test > 'should be able to resolve @shareable ProductDimension types'](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/packages/compatibility/src/tests/shareable.test.ts)
1. [override.test > 'should return overridden user name'](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/packages/compatibility/src/tests/override.test.ts)

If I run the test queries directly on the server, they all respond with the desired results.

Steps for reproducing locally:
1. `git clone git@github.com:dotansimha/graphql-yoga.git`
2. `cd graphql-yoga/examples/apollo-federation-compatibility`
3. `docker compose up`
4. `npx @apollo/federation-subgraph-compatibility docker --debug --compose docker-compose.yaml --schema schema.graphql`

**Comment by dariuszkuc** [comment]
Hello 👋 
The underlying issue is misconfigured docker compose file due to the lack of documentation on our side. When scripts were contained to just this repository, the assumption was devs would use the provided templates to create example integrations. 

Since tests are now externalized, I'll update the documentation to specify the expected service name -> service should be called `products` (vs `server` in your PR).

**Comment by enisdenjo** [comment]
Thank you, we're [all green now](https://github.com/dotansimha/graphql-yoga/actions/runs/4049096956#summary-10989710635)! 🥳

**Comment by dariuszkuc** [comment]
Added docs in https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/337
