### ISSUE TITLE
AWS AppSync compatibility tests are broken

### ISSUE THREAD

**Issue by dariuszkuc** [apollographql/apollo-federation-subgraph-compatibility#440]
Compatibility tests can no longer connect to the AWS instance. Last successful build was on 05/16.

**Comment by dariuszkuc** [comment]
@flochaz by any chance can you help us out with fixing the issue?

**Comment by flochaz** [comment]
Ah yes I know what went wrong. will fix today. Sorry about that

**Comment by flochaz** [comment]
The API Key expired, extended for one year. Will add auto refresh.

**Comment by dariuszkuc** [comment]
👋 looks like it still doesn't work? https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/449
Do we need to update the keys?

**Comment by flochaz** [comment]
no we should not have to .... hmmm will double check and get back to you

**Comment by dariuszkuc** [comment]
Fixed in #527
