### ISSUE TITLE
Found Invalid Compatibility Test Results 

### ISSUE THREAD

**Issue by DimuthuMadushan** [apollographql/apollo-federation-subgraph-compatibility#475]
We submitted the Ballerina GraphQL federation compatibility test [pull request](https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/474) to be listed among the [federation-compatible subgraph implementations](https://www.apollographql.com/docs/federation/building-supergraphs/supported-subgraphs/). Currently, the Ballerina GraphQL package doesn't support `@requires` and `@provides` directives. However, the result generated from the PR build (locally) indicates that `@requires` and `@provides` directives are supported. There seems to be an issue with the test framework.

1. Pull request - https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/474
2. Local build logs - https://github.com/MohamedSabthar/apollo-federation-subgraph-compatibility/actions/runs/5677001011/job/15384603909#step:5:224. 
 
![Screenshot from 2023-07-27 12-16-48](https://github.com/apollographql/apollo-federation-subgraph-compatibility/assets/35717653/4cf7747f-f881-4889-8325-63bc7eae4286)

**Comment by dariuszkuc** [comment]
Thanks for raising this. Existing tests were only looking at the response data so as long as the returned data matched expectations (even if it was hardcoded) tests were 🟢 .

While we won't be able to easily verify actual subgraph implementation logic, [I've updated the tests](#476) to also verify whether those directives are present in the returned `_service { sdl }` schema.
