### ISSUE TITLE
Federation 2 comparison

### ISSUE THREAD

**Issue by damienpontifex** [apollographql/apollo-federation-subgraph-compatibility#51]
Are there any requirements to add federation 2 compatibility vs federation 1?

I'm not 100% on what they might be :shrug: but is it worth pointing out compatibility e.g. `@provides` might no longer be a valid check for fed2?

**Comment by kdawgwilk** [comment]
They did mention that v2 will be backwards compatible with v1 so I think libraries would want to maintain support for both
