### ISSUE TITLE
Add @tag support to the table for schema contracts

### ISSUE THREAD

**Issue by kdawgwilk** [apollographql/apollo-federation-subgraph-compatibility#54]
It would be helpful to know which libraries support schema contracts `@tag` directive.  Would also be a good signal to maintainers to add support for it

**Comment by setchy** [comment]
I believe it `'just works` so long as you declare the schema directive in your SDL file as per [the tag spec](https://specs.apollo.dev/tag/v0.1/)

There was no need for any actual directive implementation for the use cases I've done with GraphQL Java / DGS.  Rover + Apollo Studio does the rest of the magic.

**Comment by kdawgwilk** [comment]
Ah yeah I guess some gql libs do support directives out of the gate.  I know Elixirs absinthe does not support custom directives and some other libraries prob dont but your right prob isnt a concern for this project, unless we make this more generic and have a column for `supports custom schema directives` or something

**Comment by setchy** [comment]
I think this issue can be closed now that the compatibility matrix has been updated to show fed1 / fed2
