### ISSUE TITLE
update AWS AppSync keys

### ISSUE THREAD

**Issue by dariuszkuc** [apollographql/apollo-federation-subgraph-compatibility#619]
Integration is currently broken and has been disabled in https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/618. Looks like the keys might have expired.

**Comment by dariuszkuc** [comment]
@asenousy by any chance can you help with getting new keys setup?

**Comment by asenousy** [comment]
@dariuszkuc sure thing

**Comment by asenousy** [comment]
how can i share with you the details again ?

**Comment by dariuszkuc** [comment]
Thanks! I've re-enabled the workflows.
