### ISSUE TITLE
Javascript Federation Compatibility Testing Support - mercurius/fastify

### ISSUE THREAD

**Issue by destumme** [apollographql/apollo-federation-subgraph-compatibility#66]
https://github.com/mercurius-js/mercurius

I'm planning on taking a swing at getting a PR open for this in the next few weeks, but wanted to get an issue open in case I get pulled away, or if anyone else has started any work for this.

**Comment by hwillson** [comment]
Amazing @destumme, thanks very much! Definitely let us know if you have any questions, or if there's anything we can help with.

**Comment by destumme** [comment]
Closing this, thanks for the merge!
