### ISSUE TITLE
Does order matter in entities?

### ISSUE THREAD

**Issue by olivernybroe** [apollographql/apollo-federation-subgraph-compatibility#70]
When receiving multiple representations, does it matter what order we return the entities in or should they match the order the representations are given in?

The test suite does not cover this and the specs does not either. So based on that I would assume no, but would be nice with a confirmation.

This is for the current pr #68 for adding support for Lighthouse, as we would like to know if we need to keep the order or not.

**Comment by spawnia** [comment]
Thanks @olivernybroe for creating this issue. I would like to add an example for clarification. Suppose the client requests  representations with the following input:

```json
[
  { "__typename": "Foo", "id": 1 },
  { "__typename": "Bar", "id" 1 },
  { "__typename": "Foo", "id" 2 }
]
```

Which of the following results would be acceptable?

1. Order and number of entities match, every entity found

```json
[
  { "__typename": "Foo", "id": 1 },
  { "__typename": "Bar", "id" 1 },
  { "__typename": "Foo", "id" 2 }
]
```

2. Order and number of entities match, some results are null

```json
[
  null,
  { "__typename": "Bar", "id" 1 },
  { "__typename": "Foo", "id" 2 }
]
```

3. Order matches, but a result is missing

```json
[
  { "__typename": "Bar", "id" 1 },
  { "__typename": "Foo", "id" 2 }
]
```

4. Number of entities matches, but out of order

```json
[
  { "__typename": "Bar", "id" 1 },
  { "__typename": "Foo", "id" 1 },
  { "__typename": "Foo", "id" 2 }
]
```

5. Neither order nor number of entities matches


```json
[
  { "__typename": "Foo", "id" 2 },
  { "__typename": "Bar", "id" 1 },
]
```

**Comment by kdawgwilk** [comment]
To add to those examples, one where the same entity is requested twice
```json
[
  { "__typename": "Bar", "id" 1 },
  { "__typename": "Foo", "id" 1 },
  { "__typename": "Foo", "id" 1 }
]
```

**Comment by dariuszkuc** [comment]
Hello 👋 
Return order of entities should match the order of representations. If entity cannot be resolved then it should return null for that representation.

From the examples above only 1 and 2 are valid responses.

@kdawgwilk if representations ask for the same entity multiple times, then the response should contain duplicate entries matching the request
