### ISSUE TITLE
Improve the usage documentation for maintainers

### ISSUE THREAD

**Issue by paulpdaniels** [apollographql/apollo-federation-subgraph-compatibility#84]
So some issues that I encountered when I was trying to check for spec compliance locally, that I think should be addressed to help other maintainers with their implementations.

- There aren't very clear instructions on how to run everything _without_ docker. Usually when I am testing this I am just trying to get it to run with a local instance so that I can verify the fixes that go into caliban, so I don't really want to have to deploy and run docker. There are scripts for running the user and inventory graphs, but the script for running the gateway doesn't point to a real directory (also I had to change the paths of the subgraphs because they point to dist folders that don't get built).
- The testing schemas appear inconsistent, the required one is [this](https://github.com/apollographql/apollo-federation-subgraph-compatibility#products-schema-to-be-implemented-by-library-maintainers) but the one in the reference for graphql-yoga is [this](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/implementations/graphql-yoga/products.graphql)
- There should probably be a step to have the implementation *generate* the schema, at the moment it is just sitting alongside the implementation but the two could be completely different.

**Comment by hwillson** [comment]
Great feedback @paulpdaniels, thanks! We'll be working on this shortly.

**Comment by dariuszkuc** [comment]
Hello 👋 
I've added docs on how to run local instances without docker in https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/168

> The testing schemas appear inconsistent, the required one is [this](https://github.com/apollographql/apollo-federation-subgraph-compatibility#products-schema-to-be-implemented-by-library-maintainers) but the one in the reference for graphql-yoga is [this](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/implementations/graphql-yoga/products.graphql)

With the recent changes to the test schemas we are now run better checks to ensure that subgraph schemas are correct. 

>There should probably be a step to have the implementation generate the schema, at the moment it is just sitting alongside the implementation but the two could be completely different.

We compare the schemas returned form the `_service { sdl }` query which is used by federation. Functionality is verified by running queries testing specific features against expected data set.

-----
We are always looking for feedback to make this repo better. Feel free to open new issue/s to better track outstanding problems. Contributions are always welcome!
